apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - image: ec2-3-38-115-59.ap-northeast-2.compute.amazonaws.com/admin/nginx:latest
        name: flask-example
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
