apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - name: nginx
        image: ec2-3-38-115-59.ap-northeast-2.compute.amazonaws.com/admin/nginx
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred 
